# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: "media/100px-gfdl-ms-logo_whitebg.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /blog/
- title: About
  url: /about/
- title: Blog
  url: /

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Blog Posts
    output: true
    description: |
      Welcome to the GFDL Modeling Systems blog! Read on for information about running the GFDL model, 
      getting acquainted with out team, the technologies we use (e.g. git, netCDF, Slurm), the art of
      good programming, what the team is up to, and other computing tidbits that are relevant to the 
      world of climate modeling.

      If you have an idea for a topic we should write about, or want to contribute a post of your own, 
      please open a GitHub issue.
    feature_text: |
      ## GFDL Modeling Systems
    feature_image: "media/code_banner_1600x400px.png"
